require 'yaml'

# Load default config
dir         = File.dirname(File.expand_path(__FILE__))
settings    = YAML::load_file("#{dir}/env_defaults.yaml")

# Merge env overrides if they exist
if File.exists?("#{dir}/env.yaml")
    env_settings = YAML::load_file("#{dir}/env.yaml")
    settings.merge!(env_settings)
end

Vagrant.configure("2") do |config|

    config.vm.box = "debian/bookworm64"

    config.vm.provider 'virtualbox' do |vb|
        vb.name = settings['name']
        vb.cpus = settings['cpu']
        vb.memory = settings['memory']
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end

    # Install build-essential
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install build-essential -y
        sudo apt install curl vim -y
    SHELL

    # Configure Firewall
    config.vm.provision "shell", inline: <<-SHELL
        apt remove iptables -y && apt install nftables -y
    SHELL

    # Install Helm
    config.vm.provision "shell", inline: <<-SHELL
        HELM_DOWNLOAD_URL='https://get.helm.sh/helm-v3.12.1-linux-amd64.tar.gz'
        wget "$HELM_DOWNLOAD_URL"
        tar -zxvf helm-v3.12.1-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
        rm -rf linux-amd64/helm
    SHELL

    # install k3s
    config.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://get.k3s.io | sh -
    SHELL

end